' Preview durch <Alt>d
' https://plantuml.com/de/state-diagram
' https://plantuml.com/de/guide

@startuml Zustandsdiagramm

hide empty description

state app.tsx {
    app.tsx: app

    [*] --> Home: Home

    [*] --> Login: Login/Logout

    state BuchSuchen {
        [*] --> Suchformular: Suchkriterien eingeben
        Suchformular --> Waiting: Button "Buch suchen"
        state SuchergebnisChoice <<choice>>
        Waiting --> SuchergebnisChoice: Suchergebnis eingetroffen

        state Suchergebnis {
            SuchergebnisChoice --> GefundeneBuecher: mind. 1 Buch\ngefunden
            SuchergebnisChoice --> ErrorMessage1: kein Buch\ngefunden

            ErrorMessage1 -right[hidden]-> GefundeneBuecher
        }
    }
    [*] -down-> BuchSuchen: "Buch suchen"

    state BuchAnlegen {
        [*] --> Anlegenformular: Kriterien eingeben
        Anlegenformular --> WaitingDaten: Button "Buch anlegen"
        state ErgebnisChoice <<choice>>
        WaitingDaten --> ErgebnisChoice: Kriterien eingetroffen

        state Ergebnis {
            ErgebnisChoice --> BuchAngelegt: Buch\nangelegt
            ErgebnisChoice --> ErrorMessage2: fehlerhafte Daten

            ErrorMessage2 -right[hidden]-> BuchAngelegt
        }
    }
    [*] -down-> BuchAnlegen: "Buch anlegen"

}

footer (c) Gruppe 9

@enduml
